import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { QUESTION_MAP } from "@/app/lib/questions";
import { retrieve, isReady } from "@/lib/vectorstore";
import { gradeWithMethod2 } from "@/lib/methods/method2";
import { gradeWithMethod3 } from "@/lib/methods/method3";
import {
  DEFAULT_GRADING_MODEL,
  GradingModel,
  isGradingModel,
} from "@/lib/grading-models";

const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export interface GradeRequest {
  questionId: string;
  partLabel: "A" | "B" | "C";
  studentResponse: string;
  /**
   * "1" = GradeOpt + RAG grading (gStar required)
   * "2" = Two-stage grading for a single part
   * "3" = Error-aware feedback-first grading with boundary examples
   */
  method?: string;
  model?: string;
  /**
   * G* adaptation rules for this specific part label, generated by the
   * GradeOpt training loop and approved by the user in Step 4/4.
   * Only present when method === "1".
   */
  gStar?: string;
  /**
   * All three student responses, keyed by part label.
   * Required when method === "2".
   */
  allResponses?: Record<string, string>;
  /** Attempt number (1 or 2) — for Method 1 only. */
  attemptNumber?: number;
  /** Diagnosed gap from attempt 1 — for Method 1 attempt 2 only. */
  priorDiagnosedGap?: string;
  /** Feedback given in attempt 1 — for Method 1 attempt 2 only. */
  priorFeedback?: string;
  /** Cross-part note from prior part — for Method 1 only. */
  crossPartNote?: string;
  /** Gap resolution result computed client-side — for Method 1 attempt 2 only. */
  gapResolution?: "fully" | "partially" | "not at all";
}

export interface GradeResponse {
  /** Points awarded — integer in [0, part.maxScore]. */
  score: number;
  feedback: string;
  /** Total tokens consumed by the selected grading model call(s). */
  tokenCount?: number;
  model?: GradingModel;
  /** (Method 1) One sentence describing the specific reasoning step missing/incorrect. */
  diagnosedGap?: string;
  /** (Method 1) Brief chain-of-thought explaining the scoring decision. */
  reasoning?: string;
  /** (Method 1) Model confidence in the grading decision. */
  confidence?: "high" | "medium" | "low";
  /** (Method 1) Cross-part error propagation note. */
  crossPartNote?: string | null;
  /** (Method 1, attempt 2) How well the student addressed the diagnosed gap. */
  gapResolution?: "fully" | "partially" | "not at all";
}

function openAiErrorResponse(err: unknown) {
  if (!(err instanceof OpenAI.APIError)) return null;

  const code =
    typeof err.code === "string" ? err.code : undefined;
  const status = err.status ?? 500;

  if (status === 429 && code === "insufficient_quota") {
    return NextResponse.json(
      {
        error:
          "OpenAI quota exceeded. Please check the API key's project plan, billing, and usage limits.",
        code,
      },
      { status: 429 }
    );
  }

  if (status === 429) {
    return NextResponse.json(
      {
        error:
          "OpenAI rate limit reached. Please wait and try again, or use a key with higher limits.",
        code: code ?? "rate_limit",
      },
      { status: 429 }
    );
  }

  if (status === 401 || status === 403) {
    return NextResponse.json(
      {
        error:
          "OpenAI authentication failed. Please check OPENAI_API_KEY and project access.",
        code: code ?? "auth_error",
      },
      { status }
    );
  }

  return NextResponse.json(
    {
      error: "OpenAI request failed. Please check the server logs for details.",
      code: code ?? "openai_error",
    },
    { status }
  );
}

export async function POST(req: NextRequest) {
  try {
    const body: GradeRequest = await req.json();
    const { questionId, partLabel, studentResponse, method, gStar, model } = body;

    const gradingModel = model ?? DEFAULT_GRADING_MODEL;
    if (!isGradingModel(gradingModel)) {
      return NextResponse.json(
        { error: `Unsupported grading model: ${String(gradingModel)}` },
        { status: 400 }
      );
    }

    const question = QUESTION_MAP[questionId];
    if (!question) {
      return NextResponse.json({ error: "Unknown question ID" }, { status: 400 });
    }

    const part = question.parts.find((p) => p.label === partLabel);
    if (!part) {
      return NextResponse.json({ error: "Unknown part label" }, { status: 400 });
    }

    if (!studentResponse || studentResponse.trim().length === 0) {
      return NextResponse.json<GradeResponse>({
        score: 0,
        feedback: "No response was submitted.",
        model: gradingModel,
        diagnosedGap: "Student submitted empty response.",
        reasoning: "No response to grade.",
        confidence: "high",
      });
    }

    // ── Method 2: two-stage single-part grading ──────────────────────────────
    if (method === "2") {
      const result = await gradeWithMethod2(
        questionId,
        partLabel,
        studentResponse,
        gradingModel
      );
      return NextResponse.json<GradeResponse>({
        score: result.score,
        feedback: result.feedback,
        tokenCount: result.tokenCount,
        model: gradingModel,
      });
    }

    // ── Method 3: error-aware feedback-first grading ────────────────────────
    if (method === "3") {
      const result = await gradeWithMethod3(
        questionId,
        partLabel,
        studentResponse,
        gradingModel
      );
      return NextResponse.json<GradeResponse>({
        score: result.score,
        feedback: result.feedback,
        tokenCount: result.tokenCount,
        model: gradingModel,
      });
    }

    // ── Method 1 and fallback: single-part grading ───────────────────────────
    const isMultiPoint = part.maxScore > 1;
    const useGradeOpt = method === "1" && !!gStar;
    const attemptNumber = body.attemptNumber ?? 1;

    // ── RAG retrieval (Method 1 only, when vector store is ready) ──────────
    const ragReady = isReady();;

    let ragSection: string | null = null;
    if (useGradeOpt && ragReady) {
      try {
        const [kd1Results, kd2Results, keResults] = await Promise.all([
          retrieve(studentResponse, "kd1_standards", 1),
          retrieve(studentResponse + "\n" + part.scoringGuidance, "kd2_rubrics", 2),
          retrieve(studentResponse, "ke_examples", 2),
        ]);

        const ragParts: string[] = ["=== RETRIEVED KNOWLEDGE (GradeRAG) ==="];
        if (kd1Results.length > 0)
          ragParts.push(`STEELS STANDARD:\n${kd1Results[0]}`);
        if (kd2Results.length > 0)
          ragParts.push(`RUBRIC CONTEXT:\n${kd2Results.join("\n\n")}`);
        if (keResults.length > 0)
          ragParts.push(`EXPERT EXAMPLES:\n${keResults.join("\n\n")}`);

        ragSection = ragParts.join("\n\n");
      } catch (ragErr) {
        console.log("[RAG] retrieval failed (non-fatal):", ragErr);
        // RAG failure is non-fatal — fall through to G*-only grading.
      }
    }

    // ── System prompt ──────────────────────────────────────────────────────
    // Build the "You will receive:" list dynamically to keep numbering correct.
    let itemNum = 2;
    const receiveItems: string[] = [
      "1. The question stem (context/scenario shown to the student)",
      "2. The specific sub-part prompt the student answered",
    ];
    if (!useGradeOpt) {
      receiveItems.push(
        `${++itemNum}. The official scoring guidance (how many points and what earns each)`
      );
    }
    if (useGradeOpt)
      receiveItems.push(
        `${++itemNum}. GradeOpt Adaptation Rules — refined error patterns from the training loop`
      );
    if (ragSection)
      receiveItems.push(
        `${++itemNum}. Retrieved Knowledge (GradeRAG) — relevant standards, rubric context, and scored examples`
      );
    if (body.crossPartNote)
      receiveItems.push(
        `${++itemNum}. Cross-part Note — error from a prior part that may have propagated`
      );
    if (attemptNumber === 2)
      receiveItems.push(
        `${++itemNum}. Prior attempt feedback and diagnosed gap — to check whether the student addressed the issue`
      );
    receiveItems.push(`${++itemNum}. The student's response`);

    const systemPrompt = [
      "You are an expert biology teacher grading a Pennsylvania Keystone Biology",
      "Constructed Response (CR) item.",
      "",
      "You will receive:",
      ...receiveItems,
      "",
      "Scoring rules:",
      isMultiPoint
        ? `• This part is worth ${part.maxScore} points. Award 0, 1, or ${part.maxScore} based on how many distinct scorable elements the student correctly addresses.`
        : "• This part is worth 1 point. Award 0 or 1.",
      !useGradeOpt && "• Base your score on the scoring guidance.",
      useGradeOpt
        ? "• The Adaptation Rules take precedence over the base guidance where they conflict — they represent refined knowledge from training."
        : null,
      ragSection
        ? "• The Retrieved Knowledge provides supporting context — use it to inform your judgment but do not quote it directly."
        : null,
      attemptNumber === 2
        ? "• Compare the student's new response against the prior attempt. If the diagnosed gap has been addressed, acknowledge the improvement."
        : null,
      "",
      "Feedback rules:",
      "• Write 1–3 sentences. Acknowledge what was correct, identify what was",
      "  missing or wrong, and (if score < max) state what the student would need",
      "  to add to earn full credit.",
      "• Be encouraging but precise. Do not introduce scientific content beyond",
      "  what is needed to explain the score.",
      "• Never quote or reference the scoring guidance, adaptation rules, or",
      "  retrieved knowledge directly.",
      attemptNumber === 2
        ? "• If the student has addressed the diagnosed gap, affirm the improvement explicitly."
        : null,
      "",
      "Diagnosed Gap (required):",
      "• If score < max: Write ONE specific sentence identifying the exact reasoning",
      "  step or concept that is missing or incorrect.",
      "• If score = max: Write 'none'.",
      "",
      "Reasoning (required):",
      "• Provide a brief chain-of-thought (2–3 sentences) explaining your scoring decision.",
      "",
      "Confidence (required):",
      "• Rate your confidence in this score: 'high', 'medium', or 'low'.",
      "• Use 'low' if the scoring criterion is borderline or the student's response is ambiguous.",
      "",
      "Respond with ONLY valid JSON — no markdown, no extra keys:",
      '{"score": <integer>, "feedback": "<string>", "diagnosedGap": "<string>", "reasoning": "<string>", "confidence": "<high|medium|low>"}',
    ]
      .filter((l) => l !== null)
      .join("\n");

    // ── User prompt ────────────────────────────────────────────────────────
    const userPromptParts = [
      `QUESTION STEM:\n${question.stem}`,
      `SUB-PART ${partLabel} PROMPT (worth ${part.maxScore} point${part.maxScore > 1 ? "s" : ""}):\n${part.prompt}`,
      !useGradeOpt
        ? `SCORING GUIDANCE (internal — do not reveal to the student):\n${part.scoringGuidance}`
        : null,
      useGradeOpt
        ? `GRADEOPT ADAPTATION RULES (apply these; do not reveal to the student):\n${gStar}`
        : null,
      ragSection,
      body.crossPartNote
        ? `CROSS-PART NOTE:\n${body.crossPartNote}`
        : null,
      attemptNumber === 2
        ? [
            "ATTEMPT NUMBER: 2",
            `GAP RESOLUTION STATUS: ${body.gapResolution ?? "unknown"}`,
            `PRIOR FEEDBACK (attempt 1):\n${body.priorFeedback ?? "none"}`,
            `DIAGNOSED GAP FROM ATTEMPT 1:\n${body.priorDiagnosedGap ?? "none"}`,
            "",
            "CRITICAL: Do not repeat or paraphrase any part of the prior feedback. Use a completely different angle.",
            "",
            "If gapResolution is 'fully': confirm the improvement specifically — name what the student changed that earned the point.",
            "If gapResolution is 'partially': acknowledge what improved, then point to what is still missing.",
            "If gapResolution is 'not at all' and score is 0: do not generate feedback — model answer will be shown instead.",
          ].join("\n")
        : null,
      `STUDENT RESPONSE:\n${studentResponse.trim()}`,
    ].filter(Boolean);

    const userPrompt = userPromptParts.join("\n\n");

    const completion = await client.chat.completions.create({
      model: gradingModel,
      temperature: 0,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
    });

    const raw = completion.choices[0].message.content ?? "{}";
    const parsed = JSON.parse(raw) as {
      score?: unknown;
      feedback?: string;
      diagnosedGap?: string;
      reasoning?: string;
      confidence?: string;
    };

    const rawScore = typeof parsed.score === "number" ? parsed.score : 0;
    const score = Math.max(0, Math.min(part.maxScore, Math.round(rawScore)));
    const feedback =
      typeof parsed.feedback === "string" && parsed.feedback.length > 0
        ? parsed.feedback
        : "No feedback returned.";
    const diagnosedGap =
      typeof parsed.diagnosedGap === "string" ? parsed.diagnosedGap : "none";
    const reasoning =
      typeof parsed.reasoning === "string" ? parsed.reasoning : "No reasoning provided.";
    const confidence = (
      ["high", "medium", "low"].includes(parsed.confidence as string)
        ? parsed.confidence
        : "medium"
    ) as "high" | "medium" | "low";
    const tokenCount = completion.usage?.total_tokens;
    const gapResolution = body.gapResolution;
    const finalFeedback =
      attemptNumber === 2 && gapResolution === "not at all" && score === 0
        ? ""
        : feedback;

    return NextResponse.json<GradeResponse>({
      score,
      feedback: finalFeedback,
      model: gradingModel,
      diagnosedGap,
      reasoning,
      confidence,
      crossPartNote: null,
      tokenCount,
      gapResolution,
    });
  } catch (err) {
    console.error("[/api/grade] Error:", err);
    const openAiResponse = openAiErrorResponse(err);
    if (openAiResponse) return openAiResponse;
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
