import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { QUESTION_MAP } from "@/app/lib/questions";
import { retrieve, isReady } from "@/lib/vectorstore";
import { gradeWithMethod2 } from "@/lib/methods/method2";

const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export interface GradeRequest {
  questionId: string;
  partLabel: "A" | "B" | "C";
  studentResponse: string;
  /**
   * "1" = GradeOpt + RAG grading (gStar required)
   * "2" = Two-stage batch grading (requires allResponses)
   * "3" = placeholder (falls back to base rubric grading)
   */
  method?: string;
  /**
   * G* adaptation rules for this specific part label, generated by the
   * GradeOpt training loop and approved by the user in Step 4/4.
   * Only present when method === "1".
   */
  gStar?: string;
  /**
   * All three student responses, keyed by part label.
   * Required when method === "2".
   */
  allResponses?: Record<string, string>;
}

export interface GradeResponse {
  /** Points awarded — integer in [0, part.maxScore]. */
  score: number;
  feedback: string;
  /** Total tokens consumed by the GPT-4o call (prompt + completion). */
  tokenCount?: number;
}

/**
 * Response shape returned by the /api/grade endpoint when method === "2".
 * Contains scores and feedback for all parts in one payload.
 */
export interface Method2GradeResponse {
  parts: Record<string, { score: number; feedback: string }>;
  cerNote: string | null;
  /** Total tokens across both GPT-4o calls. */
  tokenCount: number;
  /** Total latency in ms across both GPT-4o calls. */
  latencyMs: number;
}

export async function POST(req: NextRequest) {
  try {
    const body: GradeRequest = await req.json();
    const { questionId, partLabel, studentResponse, method, gStar, allResponses } = body;

    const question = QUESTION_MAP[questionId];
    if (!question) {
      return NextResponse.json({ error: "Unknown question ID" }, { status: 400 });
    }

    // ── Method 2: two-stage batch grading ────────────────────────────────────
    if (method === "2") {
      if (!allResponses) {
        return NextResponse.json(
          { error: "allResponses required for method 2" },
          { status: 400 }
        );
      }

      const result = await gradeWithMethod2(questionId, {
        A: allResponses["A"] ?? "",
        B: allResponses["B"] ?? "",
        C: allResponses["C"] ?? "",
      });

      // Build per-part response, clamping scores to each part's maxScore.
      const parts: Record<string, { score: number; feedback: string }> = {};
      for (const p of question.parts) {
        const label = p.label as "A" | "B" | "C";
        parts[label] = {
          score: Math.max(0, Math.min(p.maxScore, result.scores[label])),
          feedback: result.feedback[label],
        };
      }

      return NextResponse.json<Method2GradeResponse>({
        parts,
        cerNote: result.cerNote,
        tokenCount: result.tokenCount,
        latencyMs: result.latencyMs,
      });
    }

    // ── Methods 1 & 3: single-part grading ───────────────────────────────────
    const part = question.parts.find((p) => p.label === partLabel);
    if (!part) {
      return NextResponse.json({ error: "Unknown part label" }, { status: 400 });
    }

    if (!studentResponse || studentResponse.trim().length === 0) {
      return NextResponse.json<GradeResponse>({
        score: 0,
        feedback: "No response was submitted.",
      });
    }

    const isMultiPoint = part.maxScore > 1;
    const useGradeOpt = method === "1" && !!gStar;

    // ── RAG retrieval (Method 1 only, when vector store is ready) ──────────
    const ragReady = isReady();;

    let ragSection: string | null = null;
    if (useGradeOpt && ragReady) {
      try {
        const [kd1Results, kd2Results, keResults] = await Promise.all([
          retrieve(studentResponse, "kd1_standards", 1),
          retrieve(studentResponse + "\n" + part.scoringGuidance, "kd2_rubrics", 2),
          retrieve(studentResponse, "ke_examples", 2),
        ]);

        const ragParts: string[] = ["=== RETRIEVED KNOWLEDGE (GradeRAG) ==="];
        if (kd1Results.length > 0)
          ragParts.push(`STEELS STANDARD:\n${kd1Results[0]}`);
        if (kd2Results.length > 0)
          ragParts.push(`RUBRIC CONTEXT:\n${kd2Results.join("\n\n")}`);
        if (keResults.length > 0)
          ragParts.push(`EXPERT EXAMPLES:\n${keResults.join("\n\n")}`);

        ragSection = ragParts.join("\n\n");
      } catch (ragErr) {
        console.log("[RAG] retrieval failed (non-fatal):", ragErr);
        // RAG failure is non-fatal — fall through to G*-only grading.
      }
    }

    // ── System prompt ──────────────────────────────────────────────────────
    // Build the "You will receive:" list dynamically to keep numbering correct.
    let itemNum = 3;
    const receiveItems: string[] = [
      "1. The question stem (context/scenario shown to the student)",
      "2. The specific sub-part prompt the student answered",
      "3. The official scoring guidance (how many points and what earns each)",
    ];
    if (useGradeOpt)
      receiveItems.push(
        `${++itemNum}. GradeOpt Adaptation Rules — refined error patterns from the training loop`
      );
    if (ragSection)
      receiveItems.push(
        `${++itemNum}. Retrieved Knowledge (GradeRAG) — relevant standards, rubric context, and scored examples`
      );
    receiveItems.push(`${++itemNum}. The student's response`);

    const systemPrompt = [
      "You are an expert biology teacher grading a Pennsylvania Keystone Biology",
      "Constructed Response (CR) item.",
      "",
      "You will receive:",
      ...receiveItems,
      "",
      "Scoring rules:",
      isMultiPoint
        ? `• This part is worth ${part.maxScore} points. Award 0, 1, or ${part.maxScore} based on how many distinct scorable elements the student correctly addresses.`
        : "• This part is worth 1 point. Award 0 or 1.",
      "• Base your score on the scoring guidance.",
      useGradeOpt
        ? "• The Adaptation Rules take precedence over the base guidance where they conflict — they represent refined knowledge from training."
        : null,
      ragSection
        ? "• The Retrieved Knowledge provides supporting context — use it to inform your judgment but do not quote it directly."
        : null,
      "",
      "Feedback rules:",
      "• Write 1–3 sentences. Acknowledge what was correct, identify what was",
      "  missing or wrong, and (if score < max) state what the student would need",
      "  to add to earn full credit.",
      "• Be encouraging but precise. Do not introduce scientific content beyond",
      "  what is needed to explain the score.",
      "• Never quote or reference the scoring guidance, adaptation rules, or",
      "  retrieved knowledge directly.",
      "",
      "Respond with ONLY valid JSON — no markdown, no extra keys:",
      '{"score": <integer>, "feedback": "<string>"}',
    ]
      .filter((l) => l !== null)
      .join("\n");

    // ── User prompt ────────────────────────────────────────────────────────
    const userPromptParts = [
      `QUESTION STEM:\n${question.stem}`,
      `SUB-PART ${partLabel} PROMPT (worth ${part.maxScore} point${part.maxScore > 1 ? "s" : ""}):\n${part.prompt}`,
      `SCORING GUIDANCE (internal — do not reveal to the student):\n${part.scoringGuidance}`,
      useGradeOpt
        ? `GRADEOPT ADAPTATION RULES (apply these; do not reveal to the student):\n${gStar}`
        : null,
      ragSection,
      `STUDENT RESPONSE:\n${studentResponse.trim()}`,
    ].filter(Boolean);

    const userPrompt = userPromptParts.join("\n\n");

    const completion = await client.chat.completions.create({
      model: "gpt-4o",
      temperature: 0,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
    });

    const raw = completion.choices[0].message.content ?? "{}";
    const parsed = JSON.parse(raw) as { score?: unknown; feedback?: string };

    const rawScore = typeof parsed.score === "number" ? parsed.score : 0;
    const score = Math.max(0, Math.min(part.maxScore, Math.round(rawScore)));
    const feedback =
      typeof parsed.feedback === "string" && parsed.feedback.length > 0
        ? parsed.feedback
        : "No feedback returned.";
    const tokenCount = completion.usage?.total_tokens;

    return NextResponse.json<GradeResponse>({ score, feedback, tokenCount });
  } catch (err) {
    console.error("[/api/grade] Error:", err);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
