/**
 * POST /api/train
 *
 * Accepts the (possibly user-edited) G0 configuration as JSON and runs
 * the GradeOpt training loop.
 *
 * Returns a text/plain streaming response. Each line is either:
 *   - A human-readable progress / log message
 *   - A final DATA:<json> line carrying the GStarConfig payload
 *     (one adaptation-rules string per part label)
 *
 * In production this route should:
 *   1. Build a vector index from KD1/KD2/KE content (RAG knowledge base)
 *   2. Run the GradeOpt loop: Grader → Reflector → Refiner
 *   3. Return the refined G* adaptation rules
 * The simulated delays below stand in for that work.
 */

import { NextRequest } from "next/server";

const wait = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

export async function POST(req: NextRequest) {
  // Read the G0 config (we don't use it in the simulation, but in production
  // the training loop would consume it to build the knowledge base and run
  // iterative grading experiments).
  try {
    await req.json();
  } catch {
    // Non-critical
  }

  const encoder = new TextEncoder();
  const KD1 = 5;
  const KD2 = 3;
  const KE = 4;

  const stream = new ReadableStream({
    async start(controller) {
      const send = (line: string) =>
        controller.enqueue(encoder.encode(line + "\n"));

      // ── Phase 1: Knowledge base indexing ────────────────────────────────
      send("Building knowledge base...");
      await wait(600);
      send(`Indexing KD1: ${KD1} chunks`);
      await wait(400);
      send(`Indexing KD2: ${KD2} chunks`);
      await wait(400);
      send(`Indexing KE: ${KE} examples`);
      await wait(500);

      // ── Phase 2: GradeOpt training loop ─────────────────────────────────
      send("Starting GradeOpt training loop...");
      await wait(800);

      // Iteration 1
      send(`Iteration 1 — Grader scoring ${KE} responses...`);
      await wait(1400);
      send("Iteration 1 — Errors found: 2/4");
      await wait(600);
      send("Iteration 1 — Reflector analyzing errors...");
      await wait(1000);
      send("Iteration 1 — Refiner updating rules...");
      await wait(800);

      // Iteration 2
      send(`Iteration 2 — Grader scoring ${KE} responses...`);
      await wait(1400);
      send("Iteration 2 — Errors found: 0/4");
      await wait(400);
      send("Early stopping — all responses correct.");
      await wait(400);
      send(`Training complete. Accuracy: ${KE}/${KE}`);

      // ── G* adaptation rules ──────────────────────────────────────────────
      // In production: generated by the Refiner from real error analysis.
      const gStar: Record<string, string> = {
        A: [
          "Adaptation Rules — Part A",
          "",
          "Common Error Patterns identified during training:",
          "1. Students name 'ribosomes' as the substance — INCORRECT.",
          "   Ribosomes are the site of translation but do not carry the",
          "   genetic instructions. Do NOT award the point.",
          "2. Students say 'RNA' without specifying mRNA derived from DNA —",
          "   Do NOT award the point unless the student explicitly links RNA",
          "   back to DNA as the original instruction source.",
          "3. Students answer 'nucleus' — INCORRECT. The nucleus houses DNA",
          "   but is not itself the instructional substance.",
          "",
          "Refined Scoring Rule:",
          "Award 1 point ONLY when the response explicitly identifies DNA",
          "(or gene / genetic code / DNA sequence) as the substance",
          "containing the instructions for amino acid order.",
        ].join("\n"),

        B: [
          "Adaptation Rules — Part B",
          "",
          "Common Error Patterns identified during training:",
          "1. Students only state the protein will be 'different' or 'not",
          "   work' without explaining the structural mechanism — INSUFFICIENT.",
          "   The response must connect sequence change to folding/3-D shape.",
          "2. Students focus only on function ('the protein won't carry oxygen')",
          "   without the structural link — INSUFFICIENT for full credit.",
          "3. Students confuse primary structure (sequence) with tertiary",
          "   structure (3-D shape) without explicitly connecting them.",
          "",
          "Refined Scoring Rule:",
          "Award 1 point when the response creates an explicit chain:",
          "amino acid sequence change → different folding / 3-D shape →",
          "functional consequence. The structural link MUST be present.",
        ].join("\n"),

        C: [
          "Adaptation Rules — Part C",
          "",
          "Common Error Patterns identified during training:",
          "1. One-line answers such as 'cells need proteins' — TOO VAGUE.",
          "   Do NOT award the point.",
          "2. Students list protein types (enzymes, transport, structural)",
          "   without explaining WHY variety matters — BORDERLINE. The response",
          "   must connect diversity of types to diversity of functions.",
          "3. Students copy the stem ('proteins carry out essential functions')",
          "   without elaborating — Do NOT award the point.",
          "",
          "Refined Scoring Rule:",
          "Award 1 point when the response explicitly states that different",
          "protein types perform different/specific functions AND connects",
          "this diversity to the cell's ability to perform multiple essential",
          "biological processes.",
        ].join("\n"),
      };

      send(`DATA:${JSON.stringify(gStar)}`);
      controller.close();
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-cache, no-transform",
      "X-Accel-Buffering": "no",
    },
  });
}
